// Copyright 2017-2021 @godechain/apps authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @godechain/dev, do not edit

export const packageInfo = { name: '@godechain/apps', version: '0.98.2-88' };
